# -*- coding: utf-8 -*-
"""99_Krzywa_Forward.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8Jgjt4vIEV0vRzKIUTUZJeLAPUX_Fn3
"""

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
pd.options.plotting.backend = 'plotly'

from google.colab import files

uploaded = files.upload()

rtt_df = pd.read_csv(f'/content/rtt_prices.csv')
rtt_df.sample(5)
rtt_df['product_type'] = rtt_df['product_name'].str.extract(r'_(.)')

rtt_df.plot(x='date', y='price', color='product_name')

"""## Aktualne notowania Rynku Terminowego"""

rtt_actual = rtt_df.query("date == '2025-12-02'")
rtt_actual = rtt_actual.reset_index(drop= True)

rtt_actual

"""## Import zmiennych kalendarzowych"""

df_calendar = pd.read_csv(f'/content/calendar_hourly.csv', low_memory=False)

df_calendar.sample(10)

df_calendar_wide = df_calendar.set_index('datetimeUTC')[['product_MONTH', 'product_QUARTER', 'product_YEAR']].melt(ignore_index=False, var_name='product_type_name', value_name='product_period')

df_calendar_wide['product_name'] = ['BASE_' + _ for _ in df_calendar_wide['product_period']]

df_combine = df_calendar_wide.reset_index().merge(rtt_actual, left_on='product_name', right_on='product_name')

df_combine['datetimePL'] = pd.to_datetime(df_combine['datetimeUTC']).dt.tz_convert('Europe/Warsaw')

df_combine.pivot_table(index='datetimePL', columns='product_type', values='price').plot()

date_from = '2025-11-01'
date_to = '2025-12-02'

rtt_filtered = rtt_df[(rtt_df['date'] >= date_from) & (rtt_df['date'] <= date_to)]
sample_dates = sorted(rtt_filtered['date'].unique())
df_all = df_calendar_wide.reset_index().merge(rtt_filtered, on='product_name')
df_all['datetimePL'] = pd.to_datetime(df_all['datetimeUTC']).dt.tz_convert('Europe/Warsaw')

pivots = {date: grp.pivot_table(index='datetimePL', columns='product_type', values='price')
          for date, grp in df_all.groupby('date')}

fig = go.Figure()
for date in sample_dates:
    pivot = pivots[date]
    for ptype in ['M', 'Q', 'Y']:
        fig.add_trace(go.Scatter(
            visible=False,
            name=ptype,
            x=pivot.index if ptype in pivot.columns else [],
            y=pivot[ptype] if ptype in pivot.columns else []
        ))

for i in range(3):
    fig.data[i].visible = True

steps = [{
    "method": "update",
    "args": [{"visible": [j // 3 == i for j in range(len(fig.data))]}],
    "label": date
} for i, date in enumerate(sample_dates)]

fig.update_layout(sliders=[{"steps": steps}])
fig.update_yaxes(range=[350, 500])

fig.show()

rtt_actual.query("product_type in ['Q','Y']").sort_values('product_name')

(461.07+413.06+448.57+469.07)/4

df_quarter = df_calendar.query("year ==2026").groupby('product_QUARTER')[['datetimePL']].count()
df_quarter

year_avg = (461.07*2159+413.06*2184+448.57*2208+469.07*2209)/8760
year_avg

round(year_avg,2)

"""# Kwartały do Roku stosunek"""

rtt_actual['year'] = rtt_actual['product_name'].str[-2:].astype(int) + 2000
rtt_QvsY = rtt_actual.query("year == 2026 & product_type in ['Q','Y']")
rtt_QvsY

df_quarter

df_quarter['product_name'] = ['BASE_' + prod for prod in df_quarter.index]

df_quarter = df_quarter.merge(rtt_QvsY)

df_quarter['year_price'] = rtt_actual.query("year == 2026 & product_type == 'Y'")['price'].values[0]

df_quarter

"""### Współczynniki Kryzwej jako stosunek Kwartału do Roku"""

df_quarter['QvsY'] = df_quarter['price']/df_quarter['year_price']

df_quarter.plot(kind='line', x='product_name', y='QvsY')

"""### Współczynniki Kryzwej jako różnica Kwartału do Roku::"""

df_quarter['QvsY_diff'] = df_quarter['price'] - df_quarter['year_price']

df_quarter.plot(kind='bar', x='product_name', y='QvsY_diff')

"""## ANALIZA Q vs Y
Zbieramy dane o stosunku cen kwartalnych do rocznych dla wszystkich dat,
gdzie notowane są jednocześnie wszystkie 4 kwartały i rok.
Pozwala to na rzetelne porównanie sezonowości cen.
"""

year_target = 2026

rtt_df['product_type'] = rtt_df['product_name'].str.extract(r'_(.)')
rtt_df['year'] = rtt_df['product_name'].str[-2:].astype(int) + 2000

# Wybierz rok do analizy (zmień tę wartość aby analizować inny rok)
year_suffix = str(year_target)[-2:]

q_products = [f'BASE_Q-{i}-{year_suffix}' for i in range(1, 5)]
y_product = f'BASE_Y-{year_suffix}'
all_products_year = q_products + [y_product]

dates_with_all = rtt_df[rtt_df['product_name'].isin(all_products_year)].groupby('date')['product_name'].apply(set)
valid_dates = dates_with_all[dates_with_all.apply(lambda x: set(all_products_year).issubset(x))].index

rtt_year_filtered = rtt_df[(rtt_df['product_name'].isin(all_products_year)) & (rtt_df['date'].isin(valid_dates))]

df_calendar_hours = df_calendar.query("year == @year_target").groupby('product_QUARTER')['datetimePL'].count().reset_index()
df_calendar_hours.columns = ['quarter', 'hours']
df_calendar_hours['quarter_num'] = df_calendar_hours['quarter'].str.extract(r'Q-(\d)').astype(int)

results = []
for date in valid_dates:
    date_data = rtt_year_filtered[rtt_year_filtered['date'] == date]
    y_price = date_data[date_data['product_name'] == y_product]['price'].values[0]

    for i in range(1, 5):
        q_name = f'BASE_Q-{i}-{year_suffix}'
        q_price = date_data[date_data['product_name'] == q_name]['price'].values[0]
        hours = df_calendar_hours[df_calendar_hours['quarter_num'] == i]['hours'].values[0]
        results.append({
            'date': date,
            'quarter': f'Q{i}',
            'q_price': q_price,
            'y_price': y_price,
            'hours': hours,
            'QvsY_pct': q_price / y_price,
            'QvsY_diff': q_price - y_price
        })

df_qvsy = pd.DataFrame(results)
print(f"Analiza Q vs Y dla roku {year_target}")
df_qvsy

fig_pct = px.box(df_qvsy, x='quarter', y='QvsY_pct',
                  title=f'Q vs Y - Stosunek procentowy (dla dat z notowaniami wszystkich Q + Y-{year_suffix})',
                  labels={'QvsY_pct': 'Q/Y (%)', 'quarter': 'Kwartał'})
fig_pct.add_hline(y=1.0, line_dash="dash", line_color="red", annotation_text="Y=1.0")
fig_pct.show()

fig_diff = px.box(df_qvsy, x='quarter', y='QvsY_diff',
                   title=f'Q vs Y - Różnica (dla dat z notowaniami wszystkich Q + Y-{year_suffix})',
                   labels={'QvsY_diff': 'Q - Y (PLN/MWh)', 'quarter': 'Kwartał'})
fig_diff.add_hline(y=0, line_dash="dash", line_color="red", annotation_text="Y=0")
fig_diff.show()

"""### ANALIZA M vs Q

"""

year_target = 2025
year_suffix = str(year_target)[-2:]
quarter_months = {
    1: ['01', '02', '03'],
    2: ['04', '05', '06'],
    3: ['07', '08', '09'],
    4: ['10', '11', '12']
}

m_vs_q_results = []
for q_num, months in quarter_months.items():
    q_product = f'BASE_Q-{q_num}-{year_suffix}'
    m_products = [f'BASE_M-{m}-{year_suffix}' for m in months]
    required_products = m_products + [q_product]

    dates_with_all_mq = rtt_df[rtt_df['product_name'].isin(required_products)].groupby('date')['product_name'].apply(set)
    valid_dates_mq = dates_with_all_mq[dates_with_all_mq.apply(lambda x: set(required_products).issubset(x))].index

    rtt_mq_filtered = rtt_df[(rtt_df['product_name'].isin(required_products)) & (rtt_df['date'].isin(valid_dates_mq))]

    df_month_hours = df_calendar.query("year == @year_target").groupby('product_MONTH')['datetimePL'].count().reset_index()
    df_month_hours.columns = ['month', 'hours']

    for date in valid_dates_mq:
        date_data = rtt_mq_filtered[rtt_mq_filtered['date'] == date]
        q_price_row = date_data[date_data['product_name'] == q_product]
        if q_price_row.empty:
            continue
        q_price = q_price_row['price'].values[0]

        for m in months:
            m_product = f'BASE_M-{m}-{year_suffix}'
            m_price_row = date_data[date_data['product_name'] == m_product]
            if m_price_row.empty:
                continue
            m_price = m_price_row['price'].values[0]
            month_name = f'M-{m}-{year_suffix}'
            hours_row = df_month_hours[df_month_hours['month'] == month_name]
            hours = hours_row['hours'].values[0] if not hours_row.empty else 0

            m_vs_q_results.append({
                'date': date,
                'quarter': f'Q{q_num}',
                'month': f'M{int(m)}',
                'm_price': m_price,
                'q_price': q_price,
                'hours': hours,
                'MvsQ_pct': m_price / q_price,
                'MvsQ_diff': m_price - q_price
            })

df_mvsq = pd.DataFrame(m_vs_q_results)
print(f"Analiza M vs Q dla roku {year_target}")
df_mvsq

month_products_year = rtt_df[rtt_df['product_name'].str.contains('M-') & rtt_df['product_name'].str.endswith(f'-{year_suffix}')]['product_name'].unique()
print(f"Dostępne produkty miesięczne dla {year_target}:")
print(sorted(month_products_year))
print(f"\nLiczba dostępnych miesięcy: {len(month_products_year)}")

available_quarters = sorted(df_mvsq['quarter'].unique())
all_quarters = ['Q1', 'Q2', 'Q3', 'Q4']
missing_quarters = [q for q in all_quarters if q not in available_quarters]

n_quarters = len(available_quarters)
cols = min(n_quarters, 2) if n_quarters > 0 else 1
rows = max((n_quarters + cols - 1) // cols, 1)

quarter_labels = {'Q1': 'M1-M3', 'Q2': 'M4-M6', 'Q3': 'M7-M9', 'Q4': 'M10-M12'}
subplot_titles = [f'{q} ({quarter_labels[q]})' for q in available_quarters]

fig_mq_pct = make_subplots(rows=rows, cols=cols, subplot_titles=subplot_titles)

for i, q in enumerate(available_quarters, 1):
    row = (i - 1) // cols + 1
    col = (i - 1) % cols + 1
    df_q = df_mvsq[df_mvsq['quarter'] == q]
    for month in sorted(df_q['month'].unique()):
        df_m = df_q[df_q['month'] == month]
        fig_mq_pct.add_trace(
            go.Box(y=df_m['MvsQ_pct'], name=month, boxmean=True),
            row=row, col=col
        )

missing_str = f'; brak danych dla {", ".join(missing_quarters)}' if missing_quarters else ''
fig_mq_pct.update_layout(
    title_text=f'M vs Q {year_target} - Stosunek procentowy (dostępne: {", ".join(available_quarters)}{missing_str})',
    height=350 * rows,
    showlegend=False
)
fig_mq_pct.add_hline(y=1.0, line_dash="dash", line_color="red")
fig_mq_pct.show()

"""Box ploty M vs Q - różnica w PLN/MWh dla każdego kwartału osobno

"""

fig_mq_diff = make_subplots(rows=rows, cols=cols, subplot_titles=subplot_titles)

for i, q in enumerate(available_quarters, 1):
    row = (i - 1) // cols + 1
    col = (i - 1) % cols + 1
    df_q = df_mvsq[df_mvsq['quarter'] == q]
    for month in sorted(df_q['month'].unique()):
        df_m = df_q[df_q['month'] == month]
        fig_mq_diff.add_trace(
            go.Box(y=df_m['MvsQ_diff'], name=month, boxmean=True),
            row=row, col=col
        )

fig_mq_diff.update_layout(
    title_text=f'M vs Q {year_target} - Różnica (dostępne: {", ".join(available_quarters)}{missing_str})',
    height=350 * rows,
    showlegend=False
)
fig_mq_diff.add_hline(y=0, line_dash="dash", line_color="red")
fig_mq_diff.show()

"""### ESTYMACJA WSPÓŁCZYNNIKÓW Q vs Y
Z box plotów wyciągamy medianę jako estymator stosunku Q/Y. Mediana jest odporna na wartości odstające. Dodajemy też liczbę godzin w każdym kwartale - potrzebne do normalizacji.
"""

from scipy.stats import trim_mean
from scipy.stats.mstats import winsorize

# Funkcja agregajuąca: mean, median,
agg_funct_dict = {
  "median": lambda x: x.median(),
  "trimmed_mean": lambda x: trim_mean(x, 0.1),                 # średnia odcięta 10%
  "winsorized_mean": lambda x: winsorize(x, limits=0.15).mean(), # średnia winsorowska 10%
  "mean": lambda x: x.mean()
}

#TODO:
agg_funct = agg_funct_dict["winsorized_mean"]

qvsy_estimates = df_qvsy.groupby('quarter')['QvsY_pct'].agg(agg_funct).reset_index()

qvsy_estimates.columns = ['quarter', 'QvsY']

quarter_hours = df_calendar.query("year == @year_target").groupby('product_QUARTER')['datetimePL'].count().reset_index()
quarter_hours.columns = ['product_QUARTER', 'hours']
quarter_hours['quarter'] = 'Q' + quarter_hours['product_QUARTER'].str.extract(r'Q-(\d)')[0]

qvsy_estimates = qvsy_estimates.merge(quarter_hours[['quarter', 'hours']], on='quarter')
print("Estymaty Q vs Y (stosunek kwartału do roku):")
qvsy_estimates

"""### NORMALIZACJA WSPÓŁCZYNNIKÓW Q vs Y
Problem: surowe współczynniki Q/Y nie muszą dawać średniej ważonej = 1.0

Rozwiązanie: normalizujemy je tak, aby suma(Q_i * godziny_i) / suma(godziny) = 1.0

Dzięki temu: cena_roku = suma(cena_kwartału_i * godziny_i) / suma(godziny)

"""

def normalize_ratios(ratios, hours):
    weighted_sum = sum(r * h for r, h in zip(ratios, hours))
    total_hours = sum(hours)
    current_weighted_avg = weighted_sum / total_hours
    normalization_factor = 1.0 / current_weighted_avg
    return [r * normalization_factor for r in ratios]

raw_ratios = qvsy_estimates['QvsY'].tolist()
hours_list = qvsy_estimates['hours'].tolist()

normalized_ratios = normalize_ratios(raw_ratios, hours_list)
qvsy_estimates['QvsY_normalized'] = normalized_ratios

check_weighted_avg = sum(r * h for r, h in zip(normalized_ratios, hours_list)) / sum(hours_list)
print(f"Sprawdzenie: średnia ważona znormalizowanych Q/Y = {check_weighted_avg:.6f} (powinno być 1.0)")
print("\nZnormalizowane współczynniki Q vs Y:")
qvsy_estimates[['quarter', 'QvsY', 'QvsY_normalized', 'hours']]



"""### ESTYMACJA I NORMALIZACJA M vs Q
Analogicznie jak dla Q vs Y - wyciągamy mediany M/Q i normalizujemy.
Dla każdego kwartału osobno normalizujemy jego 3 miesiące,
tak aby średnia ważona miesięcy w kwartale = 1.0

"""

agg_funct_dict = {
  "median": lambda x: x.median(),
  "trimmed_mean": lambda x: trim_mean(x, 0.15),                 # średnia odcięta 10%
  "winsorized_mean": lambda x: winsorize(x, limits=0.10).mean(), # średnia winsorowska 10%
  "mean": lambda x: x.mean()
}

#TODO:
agg_funct = agg_funct_dict['trimmed_mean']



mvsq_estimates = df_mvsq.groupby(['quarter', 'month'])['MvsQ_pct'].agg(agg_funct).reset_index()
mvsq_estimates.columns = ['quarter', 'month', 'MvsQ']

month_hours = df_calendar.query("year == @year_target").groupby('product_MONTH')['datetimePL'].count().reset_index()
month_hours.columns = ['product_MONTH', 'hours']
month_hours['month_num'] = month_hours['product_MONTH'].str.extract(r'M-(\d+)').astype(int)
month_hours['month'] = 'M' + month_hours['month_num'].astype(str)
month_hours['quarter'] = 'Q' + ((month_hours['month_num'] - 1) // 3 + 1).astype(str)

mvsq_estimates = mvsq_estimates.merge(month_hours[['month', 'quarter', 'hours']], on=['quarter', 'month'])

mvsq_normalized_list = []
for q in mvsq_estimates['quarter'].unique():
    q_data = mvsq_estimates[mvsq_estimates['quarter'] == q].copy()
    raw_m_ratios = q_data['MvsQ'].tolist()
    m_hours = q_data['hours'].tolist()
    norm_m_ratios = normalize_ratios(raw_m_ratios, m_hours)
    q_data['MvsQ_normalized'] = norm_m_ratios
    mvsq_normalized_list.append(q_data)

mvsq_estimates = pd.concat(mvsq_normalized_list, ignore_index=True)

print("Estymaty i znormalizowane współczynniki M vs Q:")
mvsq_estimates[['quarter', 'month', 'MvsQ', 'MvsQ_normalized', 'hours']]

"""### BUDOWA KRZYWEJ FORWARD
Kluczowa operacja: M/Y = (M/Q) × (Q/Y)
Mnożąc znormalizowane współczynniki M/Q i Q/Y otrzymujemy
stosunek każdego miesiąca do ceny rocznej.
Średnia ważona M/Y powinna wynosić 1.0 (dla pełnego roku)

"""

forward_curve = mvsq_estimates.merge(
    qvsy_estimates[['quarter', 'QvsY_normalized']],
    on='quarter'
)

forward_curve['MvsY'] = forward_curve['MvsQ_normalized'] * forward_curve['QvsY_normalized']

check_forward = sum(forward_curve['MvsY'] * forward_curve['hours']) / forward_curve['hours'].sum()
print(f"Sprawdzenie: średnia ważona M/Y = {check_forward:.6f} (powinno być 1.0)")

print(f"\nKrzywa forward dla {year_target} (stosunek miesięcy do roku):")
forward_curve[['quarter', 'month', 'MvsQ_normalized', 'QvsY_normalized', 'MvsY', 'hours']]

"""### OBLICZENIE CEN MIESIĘCZNYCH
Mając współczynniki M/Y i aktualną cenę roczną z rynku,
obliczamy ceny dla każdego miesiąca:
cena_miesiąca = współczynnik_M/Y × cena_roku
"""

rtt_yearly = rtt_actual.query("product_type == 'Y'")
rtt_yearly

dfs = []
for year in rtt_yearly['product_name']:
    year_2digit = year[-2:]
    year_price = rtt_df.query(f"product_name == 'BASE_Y-{year_2digit}'")['price'].iloc[-1]

    forward_curve['year'] = int(year_2digit) + 2000
    forward_curve['month_price'] = forward_curve['MvsY'] * year_price
    forward_curve['month_num'] = forward_curve['month'].str.extract(r'M(\d+)').astype(int)
    forward_curve = forward_curve.sort_values('month_num')
    forward_curve["date"] = pd.to_datetime(forward_curve["year"].astype(str) + "-" + forward_curve["month_num"].astype(str).str.zfill(2))

    print(f"\nCeny miesięczne dla {year_2digit}:")
    print(f"Aktualna cena Y-{year_2digit}: {year_price} PLN/MWh")
    df_ = forward_curve[['month_num', 'quarter', 'MvsY', 'month_price', 'year', 'hours', 'date']]

    dfs.append(df_)
forward_curve = pd.concat(dfs)

"""### WIZUALIZACJA KRZYWEJ FORWARD
Wykres słupkowy pokazujący ceny miesięczne.
Czerwona linia przerywana = cena roczna (średnia ważona wszystkich miesięcy)

"""

forward_curve

fig_forward = px.bar(
    forward_curve,
    x='date',
    y='month_price',
    color='quarter',
    title=f'Krzywa Forward - Ceny miesięczne',
    labels={'month_price': 'Cena (PLN/MWh)', 'month': 'Miesiąc'}
)
fig_forward.show()

"""### FUNKCJA WYCENY KONTRAKTU
Wycena dowolnego okresu (np. M1-M6, Q2, H1 itp.)
Wzór: cena_kontraktu = suma(cena_miesiąca × godziny) / suma(godziny)
Jest to średnia ważona cen miesięcznych, gdzie wagą jest liczba godzin.
"""

def wycena_kontraktu(start_month, end_month, forward_curve_df):
    """
    Wycena kontraktu od start_month do end_month (włącznie).

    Parametry:
    - start_month: int (1-12)
    - end_month: int (1-12)
    - forward_curve_df: DataFrame z kolumnami 'month_num', 'month_price', 'hours'

    Zwraca:
    - średnią ważoną cenę kontraktu
    """
    contract_months = forward_curve_df[
        (forward_curve_df['date'] >= start_month) &
        (forward_curve_df['date'] <= end_month)
    ].copy()

    if contract_months.empty:
        return None, None

    total_value = (contract_months['month_price'] * contract_months['hours']).sum()
    total_hours = contract_months['hours'].sum()
    avg_price = total_value / total_hours

    return avg_price, contract_months

contract_start = "2027-01"
contract_end = "2028-04"

price, details = wycena_kontraktu(contract_start, contract_end, forward_curve)

print(f"=== WYCENA KONTRAKTU od {contract_start}-M{contract_end} {year_target} ===")
print(f"\nCena kontraktu: {price:.2f} PLN/MWh")
print(f"\nSzczegóły:")

details

"""### PORÓWNANIE WYCEN RÓŻNYCH KONTRAKTÓW
Pokazuje jak różne okresy mają różne ceny w zależności od sezonowości.

### WIZUALIZACJA WYCENY KONTRAKTU
Wykres pokazuje wszystkie miesiące (szare) oraz wybrany kontrakt (niebieskie).
Zielona linia = średnia ważona cena kontraktu
Czerwona linia = cena roczna
"""

fig_contract = go.Figure()

fig_contract.add_trace(go.Bar(
    x=forward_curve['date'],
    y=forward_curve['month_price'],
    name='Wszystkie miesiące',
    marker_color='lightgray'
))

if details is not None:
    fig_contract.add_trace(go.Bar(
        x=details['date'],
        y=details['month_price'],
        name=f'Kontrakt M{contract_start}-M{contract_end}',
        marker_color='steelblue'
    ))

    # Move the annotation for the contract price slightly above the line
    fig_contract.add_hline(
        y=price,
        line_dash="solid",
        line_color="green",
        annotation_text=f"Cena kontraktu: {price:.2f}",
        annotation_position="top left",
    )

# Offset the year price annotation to avoid overlap (on right side)
fig_contract.add_hline(
    y=year_price,
    line_dash="dash",
    line_color="red",
    annotation_text=f"Y={year_price:.2f}",
    annotation_position="bottom right",

)

fig_contract.update_layout(
    title=f'Wycena kontraktu M{contract_start}-M{contract_end} {year_target}',
    xaxis_title='Miesiąc',
    yaxis_title='Cena (PLN/MWh)',
    barmode='overlay'
)
fig_contract.show()

margin = 2.0
print(f"Sprzedam po {price+margin}")
print(f"Kupię po {price-margin}")

forward_curve[['date', 'month_price']].to_csv(f'forward_curve.csv', index=False)

